package com.jpl.fyp.classLibrary;

public enum TokenType
{
    While,
    Define,
    IntegerDeclaration,
    Integer,
    Identifier,
    OpeningParenthesis,
    ClosingParenthesis,
    OpeningBrace,
    ClosingBrace,
    Assignment,
    Plus,
    Semicolon,
    Equal,
    NotEqual,
    GreaterThan,
    LessThan,
    GreaterThanOrEqualTo,
    LessThanOrEqualTo,
    Or,
    And,
    Comma,
    If,
    Else,
    Minus,
    Multiply,
    Divide,
}
